In [1]:
import pandas as pd
data = pd.read_json('https://raw.githubusercontent.com/onaio/ona-tech/master/data/water_points.json')
df = pd.DataFrame(data)

In [2]:
df

,water_pay,respondent,research_asst_name,water_used_season,_bamboo_dataset_id,_deleted_at,water_point_condition,_xform_id_string,other_point_1km,_attachments,...,animal_point,water_mechanism_plate,water_lift_mechanism_type,road_type,water_mechanism_plate_units,water_mechanism_plate_no,water_not_functioning,water_source_type_other,simserial,subscriberid
0,no,community,Haruna Mohammed,year_round,,NaT,functioning,_08_Water_points_CV,no,[north_ghana/attachments/1351696546452.jpg],...,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,no,community,Haruna Mohmmed,year_round,,NaT,functioning,_08_Water_points_CV,yes,[north_ghana/attachments/1351701849971.jpg],...,yes,no,manual_power,gravel,NaN,NaN,NaN,NaN,NaN,NaN
2,no,community,Haruna Mohammed,year_round,,NaT,functioning,_08_Water_points_CV,yes,[north_ghana/attachments/1351702462336.jpg],...,yes,no,manual_power,paved,NaN,NaN,NaN,NaN,NaN,NaN
3,no,community,Haruna Mohammed,year_round,,NaT,functioning,_08_Water_points_CV,yes,[north_ghana/attachments/1351702971561.jpg],...,yes,no,manual_power,paved,NaN,NaN,NaN,NaN,NaN,NaN
4,no,community,Haruna Mohammed,year_round,,NaT,functioning,_08_Water_points_CV,yes,[north_ghana/attachments/1351703622326.jpg],...,yes,no,manual_power,paved,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707,no,community,Emmanuel y,year_round,,NaT,functioning,_08_Water_points_CV,no,[north_ghana/attachments/1358151218133.jpg],...,yes,no,hand_pump,NaN,NaN,NaN,NaN,NaN,NaN,NaN
708,no,local_authority community,Emmanuel y,year_round,,NaT,broken,_08_Water_points_CV,yes,[north_ghana/attachments/1358081512606.jpg],...,yes,no,hand_pump,NaN,NaN,NaN,NaN,NaN,NaN,NaN
709,no,local_authority community,Emmanuel y,year_round,,NaT,broken,_08_Water_points_CV,yes,[north_ghana/attachments/1358081512606.jpg],...,yes,no,hand_pump,NaN,NaN,NaN,NaN,NaN,NaN,NaN
710,no,community,abu seidu,year_round,,NaT,functioning,_08_Water_points_CV,no,[north_ghana/attachments/1358175596571.jpg],...,yes,no,hand_pump,NaN,NaN,NaN,NaN,NaN,8.923301e+18,6.200101e+14
711,no,community,Sa,year_round,,NaT,functioning,_08_Water_points_CV,yes,[north_ghana/attachments/1355488003808.jpg],...,yes,no,manual_power,gravel dirt,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df[['communities_villages', 'water_functioning']]

    communities_villages water_functioning
0              Gumaryili               yes
1              Selinvoya               yes
2              Selinvoya               yes
3              Selinvoya               yes
4              Selinvoya               yes
..                   ...               ...
707                 Suik               yes
708              Vundema               yes
709              Vundema               yes
710             Jiniensa               yes
711                Jagsa               yes

[712 rows x 2 columns]